### ISSUE TITLE
😱 CREATE REACT APP!!!!!

### ISSUE THREAD

**Issue by ericadamski** [brandenbortolin/brandenbortolin.github.io#2]
You are such a winner!

**Comment by brandenbortolin** [comment]
Bro I couldn't get it to load!! Damn github pages.

**Comment by ericadamski** [comment]
lmao! You gotta use www.heroku.com man! There is a react create app package that helps you set it up. https://github.com/mars/create-react-app-buildpack check it out! I spun up a site in like 3 minutes with this

**Comment by ericadamski** [comment]
Also @brandenbortolin we are looking for a new fullstack javascript developer so if you think you are tired of writing Clojure let me know :P

**Comment by brandenbortolin** [comment]
Nice, it worked for me! Any way to get that stuff onto Github Pages?

Bro, I'd be interested but you live too far. I'm moving downtown in a week. :P

**Comment by ericadamski** [comment]
NICE!! I don't think so :p

**Comment by brandenbortolin** [comment]
Where do you work again?

**Comment by ericadamski** [comment]
https://mb3online.com/
